### ISSUE TITLE
output_transform function

### ISSUE THREAD

**Issue by Vikramank** [lu-group/sbinn#8]
In the paper under Output-scaling layer, it is mentioned that 

> "magnitudes of the mean values of the ODE solution"

. But the function implementation seems different. 

`def output_transform(t, y):
        idx = 1799
        k = (data_y[idx] - data_y[0]) / (data_t[idx] - data_t[0])
        b = (data_t[idx] * data_y[0] - data_t[0] * data_y[idx]) / (
            data_t[idx] - data_t[0]
        )
        linear = torch.as_tensor(k) * t + torch.as_tensor(b)
        factor = torch.tanh(t) * torch.tanh(idx - t)
        return linear + factor * torch.Tensor([1, 1, 1e2, 1, 1, 1]) * y`

Could you please explain in detail about the methodology? Also, in the case of lab data, how would it be different?

**Comment by mitchelldaneker** [comment]
Here, we complete a scaling based on the values of the data and partially based on time. Essentially, we have found neural networks to train best when all the outputs are about the same order of magnitude. As such, in the output transform we complete a scaling to try and make the network outputs of order 1 (or range from -1 to 1), and through scaling in the output transform they will achieve their true values. 

In lab data, it will be highly dependent on your data. For an example though, say you are looking at the concentration of two species in the body, A and B. A ranges from 5 to 10, and B ranges from 0 to 1. While it would not be hard for the network to predict this, say you know these ranges. You could use the output transform such that the network output for A would range from 0 to 1. If the network outputs from 0 to 1, you simply take the output for A, multiply by 5, and add 5. This will change the output to be from 5 to 10. Again, when the network outputs ranges from -1 to 1 that works better from our experience than 0 to 1, so you can scale in that way as well.

**Comment by Vikramank** [comment]
Thanks a lot for the explanation! 
Why choose the last index(idx = 1799) for transform?

**Comment by mitchelldaneker** [comment]
In this case it is a sort of smooth scaling. If you notice we use tanh. This means that we use the scaling to reach the intended values at the initial and endpoint. It actually resembles the use of hard constraints.
